 server:
  port: 8081

  springdoc:
    swagger-ui.path: /swagger-ui.html

 moovup:
  template-endpoint: https://api.json-generator.com/templates/-xdNcNKYtTFG/data
  token: vza4lbzrzy3cyhg4nbzyjhmqzjlqr2p3qibd9986
